//
//  Strings.swift
//  BeerCatalog
//
//  Created by Evgeniy Gutorov on 3/31/19.
//  Copyright © 2019 Evgeniy Gutorov. All rights reserved.
//

import Foundation


/// In real projects this file is generated by SwiftGen from Localizable.strings https://github.com/SwiftGen/SwiftGen
enum Strings {
    enum TabBarItems {
        static let all = "All"
        static let random = "Random"
        static let favorites = "Favorites"
    }
    enum SearchBar {
        static let placeholder = "Search particular beer"
    }
    
    enum FooterView {
        static let emptyData = "No beers found"
        static let noFavorites = "You doesn't have any favorites beer"
        static let fetching = "Fetching data..."
    }
    
    enum Alert {
        static let errorTitle = "Error"
        static let okButton = "OK"
    }
}
